<a href="https://colab.research.google.com/github/ofninfo/uninove.cientedados2/blob/main/Matriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as mat
m = mat.zeros((3,2), dtype=mat.int64)
def entrada():
  m[0][0] = input("Entre com os dados da linha 1 coluna 1: ")
  m[0][1] = input("Entre com os dados da linha 1 coluna 2: ")
  m[1][0] = input("Entre com os dados da linha 2 coluna 1: ")
  m[1][1] = input("Entre com os dados da linha 2 coluna 2: ")
  m[2][0] = input("Entre com os dados da linha 3 coluna 1: ")
  m[2][1] = input("Entre com os dados da linha 3 coluna 2: ")
def mostra():
  print(m)
entrada()
mostra()

In [ ]:
import numpy as mat

m = mat.zeros((3,2))

m[0][0] = input("Entre com a altura do jogador 1: ")
m[0][1] = input("Entre com o peso do jogador 1: ")
m[1][0] = input("Entre com a altura do jogador 2: ")
m[1][1] = input("Entre com o peso do jogador 2: ")
m[2][0] = input("Entre com a altura do jogador 3: ")
m[2][1] = input("Entre com o peso do jogador 3: ")

print(m)

In [ ]:
import numpy as mat

m = mat.zeros((3,2))

for i in range(3):
  m[i][0] = input("Entre com a altura do jogador " + str(i+1) + " : ")
  m[i][1] = input("Entre com o peso do jogador " + str(i+1) + " : ")

print(m)

import numpy as mat

m = mat.zeros((3,2))

for i in range(3):
  for j in range(2):
    m[i][j] = input("Entre com a informacao da linha " + str(i) + " coluna " + str(j) + ": ")
    
print(m)

In [ ]:
import numpy as mat

salario = mat.zeros((5,3),mat.float64)

for i in range(5):
  salario[i][0] = float(input("Entre com o primeiro salário do funcionário " + str(i+1) + ": " ))
  salario[i][1] = float(input("Entre com o segundo salário do funcionário " + str(i+1) + ": " ))
  salario[i][2] = salario[i][0] + salario[i][1]

print(salario)

In [7]:
import numpy as mat

def cabecalho():
      print ("********************************************")
      print ("*        EXERCÍCIO 1: TABUADA DE 5         *")
      print ("********************************************\n")

cabecalho()

m = mat.zeros((11,3), dtype=mat.int64)

for i in range(11):
  m[i][0] = i
  m[i][1] = 5
  m[i][2] = (i * 5)

"""print(m)"""

for i in range(11):
   print(str(m[i,0]) +"\t x " + str(m[i,1]) +"\t = " + str(m[i,2]))
   

********************************************
*        EXERCÍCIO 1: TABUADA DE 5         *
********************************************

0	 x 5	 = 0
1	 x 5	 = 5
2	 x 5	 = 10
3	 x 5	 = 15
4	 x 5	 = 20
5	 x 5	 = 25
6	 x 5	 = 30
7	 x 5	 = 35
8	 x 5	 = 40
9	 x 5	 = 45
10	 x 5	 = 50


In [12]:
import numpy as mat

def cabecalho():
      print ("********************************************")
      print ("*        EXERCÍCIO 2: TABUADA DE N         *")
      print ("********************************************\n")

cabecalho()

m = mat.zeros((11,3), dtype=mat.int64)
n1 = int(input("Informe o número da tabuada: "))

for i in range(11):
  m[i][0] = i
  m[i][1] = n1
  m[i][2] = (i * n1)

"""print(m)"""

print("")

for i in range(11):
   print(str(m[i,0]) +"\t x " + str(m[i,1]) +"\t = " + str(m[i,2]))
   

********************************************
*        EXERCÍCIO 2: TABUADA DE N         *
********************************************

Informe o número da tabuada: 5

0	 x 5	 = 0
1	 x 5	 = 5
2	 x 5	 = 10
3	 x 5	 = 15
4	 x 5	 = 20
5	 x 5	 = 25
6	 x 5	 = 30
7	 x 5	 = 35
8	 x 5	 = 40
9	 x 5	 = 45
10	 x 5	 = 50


In [27]:
import numpy as mat

def cabecalho():
      print ("********************************************")
      print ("*     EXERCÍCIO 3: MATRIZ A E MATRIZ B     *")
      print ("********************************************\n")

cabecalho()

mA = mat.zeros((3,2), dtype=mat.int64)
mB = mat.zeros((3,2), dtype=mat.int64)

for i in range(3):
  for j in range(2):
    """mA[i][j] = input("Entre com a número da linha " + str(i) + " coluna " + str(j) + ": ")"""
    mA[i][j] = input("Entre com a número (" + str((i + 1)) +":"+ str(( j + 1)) + "): ")
    

n1 = int(input("\nInforme o número multiplicador: "))

print("\nMatriz A:\n",mA)

for i in range(3):
  for j in range(2):
    mB[i][j] = mA[i][j] * n1

print("\nMatriz B:\n",mB)


********************************************
*     EXERCÍCIO 3: MATRIZ A E MATRIZ B     *
********************************************

Entre com a número (1:1): 1
Entre com a número (1:2): 2
Entre com a número (2:1): 3
Entre com a número (2:2): 4
Entre com a número (3:1): 5
Entre com a número (3:2): 6

Informe o número multiplicador: 5

Matriz A:
 [[1 2]
 [3 4]
 [5 6]]

Matriz B:
 [[ 5 10]
 [15 20]
 [25 30]]


In [30]:
import numpy as mat

def cabecalho():
      print ("********************************************")
      print ("*     EXERCÍCIO 4: MATRIZ A E MATRIZ B     *")
      print ("********************************************\n")

cabecalho()

mA = mat.zeros((3,2), dtype=mat.int64)
mB = mat.zeros((2,3), dtype=mat.int64)

for i in range(3):
  for j in range(2):
    """mA[i][j] = input("Entre com a número da linha " + str(i) + " coluna " + str(j) + ": ")"""
    mA[i][j] = input("Entre com a número (" + str((i + 1)) +":"+ str(( j + 1)) + "): ")
    

n1 = int(input("\nInforme o número multiplicador: "))

print("\nMatriz A:\n",mA)

for i in range(2):
  for j in range(3):
    mB[i][j] = mA[j][i] * n1

print("\nMatriz B:\n",mB)


********************************************
*     EXERCÍCIO 3: MATRIZ A E MATRIZ B     *
********************************************

Entre com a número (1:1): 1
Entre com a número (1:2): 2
Entre com a número (2:1): 3
Entre com a número (2:2): 4
Entre com a número (3:1): 5
Entre com a número (3:2): 6

Informe o número multiplicador: 10

Matriz A:
 [[1 2]
 [3 4]
 [5 6]]

Matriz B:
 [[10 30 50]
 [20 40 60]]
