<a href="https://colab.research.google.com/github/ofninfo/uninove.cientedados2/blob/main/Vetor1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

vetor = np.array([8,34,67,98])
print(vetor)
vetor[0] = 123
vetor[1] = 456

print(vetor)

[ 8 34 67 98]
[123 456  67  98]


In [4]:
def entrada():
  a1 = input("Entre com a altura do Jogador 1:")
  a2 = input("Entre com a altura do Jogador 2:")
  a3 = input("Entre com a altura do Jogador 3:")
  a4 = input("Entre com a altura do Jogador 4:")
  a5 = input("Entre com a altura do Jogador 5:")


  entrada()

In [14]:
import numpy as vet

a = vet.zeros(5)

def entrada():
  for i in range(5):
    a[i] = input("Entre com a altura do Jogador:")
  print(a)
  
entrada()

Entre com a altura do Jogador:2
Entre com a altura do Jogador:5
Entre com a altura do Jogador:6
Entre com a altura do Jogador:8
Entre com a altura do Jogador:4
[2. 5. 6. 8. 4.]


In [15]:
import numpy as vet

a = vet.zeros(5)

def entrada():
  for i in range(5):
    a[i] = input("Entre com a altura do Jogador "+ str(i+1) +": ")
  
entrada()

Entre com a altura do Jogador 1: 2
Entre com a altura do Jogador 2: 3
Entre com a altura do Jogador 3: 5
Entre com a altura do Jogador 4: 7
Entre com a altura do Jogador 5: 5


In [18]:
import numpy as vet

a = vet.zeros(5)

def entrada():
  for i in range(5):
    a[i] = input("Entre com a altura do Jogador "+ str(i+1) +": ")
  
def media_idade():
  soma_idade = 0
  for i in range(5):
    soma_idade+=a[i]
  print(soma_idade)

entrada()
media_idade()


Entre com a altura do Jogador 1: 1.8
Entre com a altura do Jogador 2: 1.9
Entre com a altura do Jogador 3: 1.75
Entre com a altura do Jogador 4: 1.95
Entre com a altura do Jogador 5: 2
9.4


In [25]:
import numpy as vet

notas = vet.zeros(10)

def entrada():
  for i in range(7):
    notas[i] = input("Nota do Aluno "+ str(i+1) +": ")

def media_nota():
  soma_nota=0
  aluno_acima_media=0

  for i in range(7):
    soma_nota+=notas[i]
  
  media = soma_nota/7
  print("A média de notas é: ",round(media,2))

  for i in range(5):
    if (notas[i] > media):
      aluno_acima_media+=1
  print("Quantidade de alunos média de notas é: ",aluno_acima_media)

entrada()
media_nota()

Nota do Aluno 1: 5
Nota do Aluno 2: 5
Nota do Aluno 3: 5
Nota do Aluno 4: 6
Nota do Aluno 5: 4
Nota do Aluno 6: 3
Nota do Aluno 7: 5
A média de notas é:  4.71
Quantidade de alunos média de notas é:  4
